Encodings.md
src/main/thrift/parquet.thrift

PARQUET-323: Mark INT96 as deprecated

---

Encodings.md

RLE_DICTIONARY is never mentioned in Encodings.md yet is the recommended
enum value to use in Parquet 2.0.

Update Encodings.md with RLE_DICTIONARY

---

.travis.yml
pom.xml

Use default (latest) distribution for Travis (as of now Trusty) to make tests pass. Looks like for Precise JDK 1.7 is the default Java version, where TLSv1 is the default, and it is not supported by Maven Central anymore. With Trusty, the build runs with JDK 1.8, and tests pass.

PARQUET-1351: Travis builds fail for parquet-format

---

LogicalTypes.md
src/main/thrift/parquet.thrift

Introduce new nanosecond precision in TimeUnit

PARQUET-1387: Nanosecond precision time and timestamp - parquet-format

---

src/main/thrift/parquet.thrift

Revert columnar encryption changes for parquet-format release.
Since we don't have any signed-off spec for columnar encryption, and the spec is in fact still changing, revert these PRs and continue the development of columnar encryption on separate feature branch. This branch should be merged once the spec is signed off and it is ready to be released, this way this doesn't hinder parquet-format release.

PARQUET-1428: Move columnar encryption into its feature branch 

---

BloomFilter.md
src/main/thrift/parquet.thrift

Move original PR to here and add doc.

PARQUET-41: Add Bloom filter

---

src/main/thrift/parquet.thrift

The documentation for list<ColumnOrder> column_orders stated that "Each
sort order corresponds to one column, determined by its position in the
list, matching the position of the column in the schema."
However, in reality, while the order of elements in these two
lists (schema and sort order) are the same, only leaf nodes are
represented in the list of sort orders, so the positions do not match.

PARQUET-1437: Misleading comment in parquet.thrift

---

LogicalTypes.md
src/main/thrift/parquet.thrift

Clarify in the comments that we should only map the new TIMESTAMP type
to the old TIMESTAMP_MILLIS or TIMESTAMP_MICROS types when the semantics
match (UTC normalized and the precision matches).

PARQUET-1487: Do not write original type for timezone-agnostic timestamps

---

README.md
src/main/thrift/parquet.thrift

Although a page-level CRC field is defined in the Thrift specification, currently neither parquet-cpp nor parquet-mr leverage it. Moreover, the comment in the Thrift specification reads ‘32bit crc for the data below’, which is somewhat ambiguous to what exactly constitutes the ‘data’ that the checksum should be calculated on. To ensure backward- and cross-compatibility of Parquet readers/writes which do want to leverage the CRC checksums, the format should specify exactly how and on what data the checksum should be calculated.
**TLDR proposal:** The checksum will be calculated using the standard CRC32 algorithm, whereby the checksum is to be calculated on the data only, not including the page header itself (simple implementation) and the checksum will be calculated on compressed data …

PARQUET-1539: Clarify CRC checksum in page header

---

Encodings.md

Addressed most points in PARQUET-1561.
We should add examples containing multiple miniblocks and blocks.

PARQUET-1561: Inconsistencies in the Delta Encoding specification

---

Encodings.md

In commit 0622c460f82ddb41f5d38992fd26a20de10744e1 I left some brackets around hyperlinks. I'm removing those.

PARQUET-1561: Remove erroneous brackets.

---

.gitignore
.travis.yml
pom.xml

`parquet-mr` is at Thrift 0.12.0 as well.
https://jira.apache.org/jira/browse/PARQUET-1507
This also fixes the CVE-2018-1320 https://cve.mitre.org/cgi-bin/cvename.cgi?name=2018-1320

PARQUET-1588: Bump to Apache Thrift 0.12.0

---

src/main/thrift/parquet.thrift

Rename bloom filter hash from murmur3 to murmur3hash.

PARQUET-1592: rename bloom filter hash

---

.github/PULL_REQUEST_TEMPLATE.md
pom.xml

- https://issues.apache.org/jira/browse/PARQUET-1579

PARQUET-1579: Add Github PR template

---

.travis.yml
pom.xml

https://jira.apache.org/jira/browse/PARQUET-1499
https://jira.apache.org/jira/browse/PARQUET-1590
Depends on #133

PARQUET-1590: Add Java 11 to Travis

---

BloomFilter.md
src/main/thrift/parquet.thrift

- My PR addresses Jira(https://issues.apache.org/jira/browse/PARQUET-1609) issue and references them in the PR "PARUQET-1609: Add xxHash as an option to bloom-filter hash strategy"

PARUQET-1609: Update to use xxHash as hash strategy

---

BloomFilter.md

This PR addresses [PARQUET-1617](https://issues.apache.org/jira/browse/PARQUET-1617) .

PARQUET-1617: Add more detail to Bloom filter spec

---

BloomFilter.md

The hash function "xxhash" is actually a number of different hash
functions including xxHash, XXH64, XXH32, and XXH3. Additionally,
these hash functions accept "seeds", as most modern hash functions do,
including MurmurHash variants.
This patch specifies that the BloomFilter hash function default is
XXH64 with a seed of 0. It omits the confusing note about the ISA and
different variants of xxHash, since XXH64 is apparently
architecture-independent.
1. Subject is limited to 50 …

PARQUET-1609: Specify which xxhash carefully

---

LogicalTypes.md
src/main/thrift/parquet.thrift

PARQUET-1627: Update specification so that legacy timestamp logical types can be written for local semantics as well

---

BloomFilter.md

The specific questions answered from
https://lists.apache.org/thread.html/82d2e50f8c1007720564c5dc64aeae7947e949f3954a83436dc36760@%3Cdev.parquet.apache.org%3E
are
How is the bloom filter block selected from the 32 most-significant
bits from of the hash function? These details must be in the spec and
not in papers linked from the spec.
How is the number of blocks determined? From the overall filter size?
I think that the exact procedure for a lookup in each block should be
covered in a section, followed by a section for how to perform a look
up in the multi-block filter. The wording also needs to be cleaned up
so that it is always clear whether the filter that is referenced is a
block or the multi-block filter.
The spec should give more detail on how to choose the number of blocks
and on …

PARQUET-1630: Clarify the Bloom filter algorithm

---

BloomFilter.md
src/main/thrift/parquet.thrift

Right now no compression methods are supported. For more on Bloom
filter compression, see Michael Mitzenmacher's "Compressed Bloom
Filters",
https://www.eecs.harvard.edu/~michaelm/NEWWORK/postscripts/cbf2.pdf

PARQUET-1630: add empty compression union for Bloom filter

---

BloomFilter.md

This patch uses a range reduction trick to produce a pseudorandom
number within an index without using the modulo operator '%', which is
often very slow.
The oldest reference I know to this trick is Kenneth A. Ross's IBM
research report from 2006, "Efficient Hash Probes on Modern
Processors", available at
https://domino.research.ibm.com/library/cyberdig.nsf/papers/DF54E3545C82E8A585257222006FD9A2/$File/rc24100.pdf

PARQUET-1630:  Loosen size restrictions on Bloom filters

---

README.md

Link to "How To Contribute" section in Parquet-MR project would return
404 error as the URL would be incorrectly expanded to
https://github.com/apache/parquet-format/blob/master/github.com/apache/parquet-mr
instead of https://github.com/apache/parquet-mr which is the assumed
desired destination
This change should take one directly to the "How To Contribute" section
in the Parquet-MR README
modified:   README.md
- https://issues.apache.org/jira/browse/PARQUET-1672
1. Subject is limited to 50 characters (not including Jira issue …

PARQUET-1672: [DOC] Fix broken link in README.md

---

dev/finalize-release
dev/prepare-release.sh
dev/source-release.sh

Update prepare-release.sh to create RC tags and keep using the current
RC version with SNAPSHOT for development.
Update source-release.sh to retrieve the hash of the RC tag.
Create the new script finalize-release to create the final release tag
and update the development version.

PARQUET-1687: Update release process

---

Encodings.md
src/main/thrift/parquet.thrift

As discussed in the Jira issue, it would be a great benefit for better compression ratio and speed to add an encoding for FP data.

PARQUET-1622: Add BYTE_STREAM_SPLIT encoding

---

src/main/thrift/parquet.thrift

https://issues.apache.org/jira/browse/PARQUET-1708

PARQUET-1708: Fix Thrift compiler warning

---

src/main/thrift/parquet.thrift

Statistics in DataPageHeaderV2 should be about the page, not column chunk.

PARQUET-1862: fix comment mistake of DataPageHeaderV2

---

src/main/thrift/parquet.thrift

Mention that CRC is calculated after compression and encryption

PARQUET-1892: Update Thrift comment to explain CRC calculation in encrypted columns

---

LogicalTypes.md

The written spec shouldn't diverge from the Thrift definitions.

PARQUET-2011: Use "unit" for timestamp parameter, not "precision"

---

LogicalTypes.md
README.md
src/main/thrift/parquet.thrift

Also slight wording improvements, and replace a "must" with "should" for writing the ConvertedType field.

PARQUET-2013: [Format] Mention that ConvertedType is deprecated

---

PageIndex.md
src/main/thrift/parquet.thrift

PARQUET-2016: Reference column_order field from column indexes

---

README.md
src/main/thrift/parquet.thrift

PARQUET-2034: Document dictionary page position

---

Encodings.md

Also word-wrapping for better source readability and editability.

PARQUET-2215: [Format] Document overflow handling in DELTA_BINARY_PACKED

---

README.md
src/main/thrift/parquet.thrift

- [x ] My PR addresses the following [Parquet Jira](https://issues.apache.org/jira/browse/PARQUET/) issues and references them in the PR title. For example, "PARQUET-1234: My Parquet PR"

PARQUET-1222: [Format] Add details about sort order to README.md

---

src/main/thrift/parquet.thrift

A small spelling fix I found while reading the spec (I figured this trivial enough to skip JIRA tracking). I'm really enjoying the thorough comments, by the way 😄.

MINOR: Typo in parquet.thrift

---

LogicalTypes.md

I'm pretty sure that, under "Unsigned Integers", we should say
> …and `INT(64, false)` must annotate…
rather than
> …and `INT(64, true)` must annotate…

Fix typo under "Unsigned Integers"

---

Encodings.md

DELTA_BYTE_ARRAY has been supported for FIXED_LEN_BYTE_ARRAY by parquet-mr since 2015 (see PARQUET-152). Update the spec in consequence.
Also improve wording, markup and add an example.

PARQUET-2231: [Format] Allow DELTA_BYTE_ARRAY for FIXED_LEN_BYTE_ARRAY

---

Encodings.md
README.md

Propose to explicitly state that no padding is allowed within a data page. This makes it easier  for BYTE_STREAM_SPLIT decoder to decode page with nulls. In this way, it can simply get the number of encoded values by `total_length_encoded_stream / K (4 for float and 8 for double)`. Otherwise, it has to decode def/rep levels to get exact number of non-null values.

PARQUET-2241: Update wording of BYTE_STREAM_SPLIT encoding

---

README.md

Add missing FIXED_LEN_BYTE_ARRAY type under Types in README.md

MINOR: Add FIXED_LEN_BYTE_ARRAY Type

---

Encodings.md

**JIRA:**
https://issues.apache.org/jira/browse/PARQUET-2222
**Problem:**
The spec (https://github.com/apache/parquet-format/blob/master/Encodings.md#run-length-encoding--bit-packing-hybrid-rle--3) has this:
```
rle-bit-packed-hybrid: <length> <encoded-data>
length := length of the <encoded-data> in bytes stored as 4 bytes little endian (unsigned int32)
```
But the length is actually prepended only in v1 data pages, not in v2 data pages.
**Implementation:**
parquet-mr: https://github.com/apache/parquet-mr/blob/master/parquet-column/src/main/java/org/apache/parquet/column/impl/ColumnWriterV2.java#L41
parquet-cpp: https://github.com/apache/arrow/blob/main/cpp/src/parquet/column_writer.cc#L848
**Proposal:**
Explicitly get rid of the confusion in the RLE encoding spec.

PARQUET-2222: RLE encoding spec incorrect for v2 data pages

---

src/main/thrift/parquet.thrift

The specs has only added `bloom_filter_offset` to locate the bloom filter. The reader cannot load the bloom filter in a single shot until it parses the bloom filter header to get the total size.
```thrift
struct ColumnMetaData {
/** Byte offset from beginning of file to Bloom filter data. **/
14: optional i64 bloom_filter_offset;
}
```
This patch proposes to add an optional bloom_filter_length field to track the size of bloom filter to facilitate I/O scheduling. The specs already do the similar things for column index and offset index.

PARQUET-2257: Add bloom_filter_length to ColumnMetaData

---

pom.xml

So we have the latest versions and we are Java 17 compatible

PARQUET-2271: Bump Apache POM to 29

---

LogicalTypes.md
src/main/thrift/parquet.thrift

The majority of implementations allow for scale == precision.
See https://github.com/apache/arrow-rs/pull/1607 for further motivation.

PARQUET-2264: Allow scale == precision for DecimalType

---

src/main/thrift/parquet.thrift

I noticed that the default value for the optional boolean `is_compressed` field of the `DataPageHeaderV2` struct has a default value of `1`. According to the Thrift docs a boolean value is either `true` or `false`. 
This currently works because the Apache Thrift compiler internally handles bools as ints:
- https://github.com/apache/thrift/blob/3880a09565a9a1dad028b3679746eafac268c819/compiler/cpp/src/thrift/thriftl.ll#L208-L209
- https://github.com/apache/thrift/blob/3880a09565a9a1dad028b3679746eafac268c819/compiler/cpp/src/thrift/main.cc#L748
It may however not work with other Thrift compilers that are more strict about this.
Based on the docs and [a test](https://github.com/apache/thrift/blob/3880a09565a9a1dad028b3679746eafac268c819/test/ThriftTest.thrift#L406) in the Thrift repository …

PARQUET-2299: Use `true` instead of `1` as default value for `is_compressed` bool field

---

.github/workflows/test.yml
pom.xml
src/main/java/org/apache/parquet/format/InterningProtocol.java

This should support Java 8 again
- https://issues.apache.org/jira/browse/PARQUET-2344

PARQUET-2344: Bump to Thrift 0.19.0

---

Encodings.md

> Dictionary page format: the entries in the dictionary - in dictionary order - using the [plain](#PLAIN) encoding.
The dictionary entries are not sorted (or at least not always sorted).
> There is no padding between values (except for the last byte) which is padded with 0s.
Minor change.

PARQUET-2362: Clarify parquet encoding

---

src/main/thrift/parquet.thrift

- https://issues.apache.org/jira/browse/PARQUET-2352
This updates the spec to allow truncation of row group min_values/max_value statistics so that readers can take advantage of row group pruning for predicates on columns containing long strings.
https://issues.apache.org/jira/browse/PARQUET-1685 already introduced a feature to parquet-mr which allows users to deviate from the current spec and configure truncation of row group statistics.
This change also adds is_max_value_exact/is_min_value_exact to allow writers to specify
when the max_value/min_value are the actual max and min values found on the column chunk.
Since the possibility of truncation exists and is not possible to explicitly detect, attempts to pushdown min/max aggregation to parquet have avoided implementing it for string …

PARQUET-2352: Allow truncation of row group min_values/max_value statistics

---

LogicalTypes.md
src/main/thrift/parquet.thrift

In the Mailing List, I proposed the addition of a Half Float (float16) type in Parquet: https://lists.apache.org/thread/03vmcj7ygwvsbno764vd1hr954p62zr5
This type is becoming increasingly popular in Machine Learning, and there are a bundle of issues requesting its support in Parquet:
https://issues.apache.org/jira/browse/PARQUET-1647
https://issues.apache.org/jira/browse/PARQUET-758
https://issues.apache.org/jira/browse/ARROW-17464
https://github.com/apache/arrow/issues/2691
This is my first logical type proposal! I followed [this PR](https://github.com/apache/parquet-format/pull/71) as inspiration, but really welcome feedback from the community.
Implementation PRs:
* C++ https://github.com/apache/arrow/pull/36073
*****
1. Subject is separated …

PARQUET-758: Add Float16/Half-float logical type

---

Compression.md

See https://github.com/apache/parquet-testing/pull/41 for more context

PARQUET-2369: Clarify GZIP Support for Multiple GZIP Members

---

CHANGES.md

PARQUET-2379: [Format] Update changelog for 2.10.0

---

src/main/thrift/parquet.thrift

Fixing parquet.thrift doc of sort order for INTERVAL to reflect change made by https://github.com/apache/parquet-format/commit/c6d306daad4910d21927b8b4447dc6e9fae6c714
Figured this is trivial enough change to skip need for JIRA issue, but let me know if otherwise

MINOR: Fix INTERVAL sort order doc in parquet.thrift to be undefined

---

Compression.md

- Add missing word: codecs
- Add line break to keep the ~72 characters per line

MINOR: Fix missing word in Compression

---

README.md

https://issues.apache.org/jira/browse/PARQUET-2479
As part of clarifying and improving the public communication about Parquet, I think we should also link parquet-format to the parquet.apache.org website
Also, the text in the format repo's readme is somewhat unclear on what is in the repo and how it related to other projects, so I clarified that as well
You can see the rendered version of the README here:
https://github.com/alamb/parquet-format/tree/alamb/doc_link_readme?tab=readme-ov-file#parquet-
- https://issues.apache.org/jira/browse/PARQUET-2479
1. Subject is limited to 50 …

PARQUET-2479: Update README with link to parquet website, clarify contents

---

PageIndex.md
src/main/thrift/parquet.thrift

https://issues.apache.org/jira/browse/PARQUET-2480
See the proposed update as rendered markdown: https://github.com/alamb/parquet-format/blob/alamb/page-index/PageIndex.md 
I have always found it very confusing that people refer to the term parquet "page index", for example [this message](https://lists.apache.org/thread/o9nxbmv1z4hph3v5s2z63jsklywpkyyj,)
However, the term "page index" is not used in the the [parquet.thrift](https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift) file itself, but only appears as the name of the file that describes the `ColumnIndex` and `OffsetIndex`, [PageIndex.md](https://github.com/apache/parquet-format/blob/master/PageIndex.md)
This means I can't search for "page index" in the spec and find out what people are talking about …

PARQUET-2480: Clarify what "page index" means in Parquet.thrift

---

src/main/thrift/parquet.thrift

As discussed on the mailing list ([thread link](https://lists.apache.org/thread/0gxjk4tphxls0gcrc7lt775pf8s7gtz3)) , parquet.thrift uses the terms `record` and `row` to mean the same thing, which could cause confusion
The consensus on the mailing list was to use the term "row".
This PR proposes changing `parquet.thrift` so it only uses the term 'row'
- https://issues.apache.org/jira/browse/PARQUET-2488
1. …

PARQUET-2488: Use term `row` consistently in `parquet.thrift`

---

Encryption.md

Follow up on this [thread](https://github.com/apache/arrow/pull/41821#issuecomment-2146869828).

PARQUET-2491: Address AES GCM invocation limit in encryption spec

---

LogicalTypes.md
README.md
src/main/thrift/parquet.thrift

Changes instances of 'binary' to BYTE_ARRAY where appropriate. Also fixes some uses of FIXED_LEN_BYTE_ARRAY.
- https://issues.apache.org/jira/browse/PARQUET-2485

PARQUET-2485: Be more consistent with BYTE_ARRAY types

---

README.md
src/main/thrift/parquet.thrift

An alternative to #439
Related to [parquet-java/#2678](https://github.com/apache/parquet-java/issues/2678) and https://github.com/apache/parquet-java/pull/1369
See mailing list discussion at https://lists.apache.org/thread/r6r2cvzrdoorq6h6gqwh0b1hbfbhxv29
- https://issues.apache.org/jira/browse/PARQUET-2139

PARQUET-2139: Deprecate ColumnChunk::file_offset field

---

pom.xml

- https://issues.apache.org/jira/browse/PARQUET-2481

PARQUET-2481: Bump to Apache parent POM 32

---

pom.xml

Apart from the original authors' great work, Apache projects should not mention any contributors in particular in the POM.
- https://issues.apache.org/jira/browse/PARQUET-2482

PARQUET-2482: Remove `<developers>` from the POM

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/ISSUE_TEMPLATE/usage_question.yaml
.github/PULL_REQUEST_TEMPLATE.md

As we have migrated from JIRA to GitHub issues, it would be good to provide issue template similar to parquet-java repo.
Add GitHub issue template and modify PR template.
Not a format change.
Closes #443

GH-443: Add GitHub issue template

---

CONTRIBUTING.md

- https://issues.apache.org/jira/browse/PARQUET-2489

PARQUET-2489:  Guidance on feature releases

---

src/main/thrift/parquet.thrift

Clarify num-nulls handling. I've mentioned this in maillist: https://lists.apache.org/thread/oqd9lt7p0jtf217hg0667xhk0zvwbgvt
Suggest writer to have num_nulls/null_count
no

Clarify num-nulls handling in Statistics and ColumnIndex

---

Encryption.md

Encrypted files use three types of ordinals: row group, column, page. All three are simple local counters in both writers and readers. In addition, the row group ordinal is stored in the parquet footer (RowGroup.ordinal field). Parquet implementors can benefit from a clarification on the reason for and intended use of this field.

GH-452: Clarify use of RowGroup.ordinal field

---

VariantEncoding.md
VariantShredding.md

Spark and Parquet communities have agreed to move the Spark Variant spec to Parquet.
Added the Variant specification docs.
Closes #455

GH-455: Add Variant specification docs

---

LogicalTypes.md

Typo in documentation
typo: LogicalTypes.md -- s/is used to for/is used for/
No

MINOR: typo: LogicalTypes.md -- s/is used to for/is used for/

---

VariantEncoding.md
VariantShredding.md

Add more clarification and justification for various aspects of the Variant specification.
Details and clarification to the Variant spec. Addressing some feedback from previous PR: https://github.com/apache/parquet-format/pull/456

[FOLLOWUP] Clarify Variant specification details

---

LogicalTypes.md

The specification of the MAP logical type is unclear in some points and makes it hard for the implementations to properly identify and handle such structures.
Extend the MAP specification to be more clear.
Not required
Closes #468

GH-468: Clarify MAP logical type

---

VariantEncoding.md

We should clarify whether metadata integers are signed or unsigned.
Clarify signedness for Variant types
Not this is still WIP

MINOR: Clarify offsets etc are unsigned integers

---

LogicalTypes.md

The C++ reader of parquet-cpp is having a hard time to read Parquet file written by parquet-java with `parquet.avro.write-old-list-structure=true` and schema below:
```
optional group a (LIST) {
repeated group array (LIST) {
repeated int32 array;
}
}
```
See https://github.com/apache/arrow/issues/43994 and https://github.com/apache/arrow/pull/43995
Clarify the rules for various list types.
1. Unannotated repeated fields.
```
repeated int32 num_list;
repeated group my_list {
required int32 num;
optional binary str (STRING);
}
```
2. LIST-annotated 2-level structures.
```
<list-repetition> group <name> (LIST) {
repeated <element-type> <element-name>;
}
list-repetition: can be repeated, required, and optional.
```
Not required
Closes #465

GH-465: Clarify backward-compatibility rules on LIST type

---

VariantEncoding.md

Iceberg tables support time, nano timestamps, UUID types and currently Variant spec doesn't include those. Propose to add those missing types.
The spec change.
Fix #463

GH-463: Add more types - time, nano timestamps, UUID to Variant spec

---

VariantShredding.md

Seems the example included in shredding spec is not correct. 123 in row 3 and 4 can be shredded. Correct them to avoid confusion.
Closes #477

Update example in shredding spec 

---

README.md

While reading the README file I found that `parquet-compatibility` seems to be a wrong component and should be `parquet-testing`.
I also think adding links can help navigation for users interested while reading the README file.
- Update from `parquet-compatibility` to `parquet-testing`
- Add links to different projects
Not required

MINOR: Add links to projects on README and update parquet-compatibility to parquet-testing

---

VariantEncoding.md

There were some unnecessary gaps in the Variant type id numbering. This removes the id number gaps.
Also, some trivial spacing/formatting changes.
Updates to the Variant binary encoding spec.
n/a

MINOR: Remove Variant type id gaps

---

VariantEncoding.md

I've talked with several community members that intend to implement JSON conversion, but do not want the conversion specified in the Variant spec to be required. If the conversion is not required, I don't think that it makes sense to add it to the spec.
The conversion was originally added because we wanted to ensure that engines that do not support Variant could interact with the data. At the time, it seemed like a good idea to standardize how conversion to JSON took place for those engines. But there is necessarily data loss when converting to JSON. It's hard to decide just how lossy this conversion (to JSON and back) should be and what value there is to minimizing the loss. That's why people don't intend to implement a consistent well-defined conversion. Without willingness to follow …

Variant: Remove JSON conversion table

---

VariantShredding.md

GH-486: Variant object shredding without field shredding

---

src/main/thrift/parquet.thrift

Add a unified version for variant spec (shredding and binary version).
Variant is still work in progress.
Closes #473

GH-473: Add  variant version

---

VariantShredding.md

I believe _homogeneous_ is the correct word to describe data that shares a common type or characteristic and _homogenous_ is a common misspelling.  
Other sources use this spelling
https://docs.aws.amazon.com/whitepapers/latest/aws-cloud-data-ingestion-patterns-practices/homogeneous-data-ingestion-patterns.html 
https://www.dremio.com/wiki/homogeneous-data/

MINOR: Replace homogenous with homogeneous

---

README.md
src/main/thrift/parquet.thrift

This PR contains the small documentation fixes that were pulled out of [PR#221](https://github.com/apache/parquet-format/pull/221), [as it was suggested](https://github.com/apache/parquet-format/pull/221#discussion_r1451853168) that they should go into an own PR.
Mostly, this is small format and and content fixes. The only larger change is that the explanation of comparison rules was deduplicated out of `LogicalTypes.md`, as the same text is also in `parquet.thrift` and keeping such duplicate documentation in sync is hard. Instead, `LogicalTypes.md` just points to `parquet.thrift`. Deduplicating this is especially important for PR#221, as that PR introduces a new column ordering and thus makes the ordering rules even larger, so having them duplicated is becoming even a bigger burden.

Minor: Small documentation fixes and deduplication

---

Geospatial.md

Update the specification to offer clearer instructions on how writers should populate bounding box values in the presence of NaNs, and how readers should interpret missing or incomplete bounding boxes.
Added comments in the `Bounding Box` section of the `Geospatial.md`.
Below is an example illustrating how bounding box statistics behave based on the presence of X and Y values:
All values in this example file are allowed by WKB encoding.
```
--- Parquet file
file-level bbox: [1, 9, 100, 900]
-- Row group 1
row-group bbox 1: [1, 2, 100, 100]
POINT (1, 100)
POINT (2. NaN)
-- Row group 2
row-group bbox 2: [3, 3, 300, 300]
POINT (3, 300)
POINT (NaN, NaN)
-- Row group 3
row-group bbox 3: no bbox
POINT (5, NaN)
POINT (6, NaN)
-- Row group 4
row-group bbox 4: [7, 8, 700, 800]
POINT (7, 700)
POINT …
```

GH-493: Clarify Bounding Box Behavior in GeospatialStatistics 

---

VariantEncoding.md

Fix verb tense to match `type`
I noticed a small typo in the opening lines of the spec while working on the Rust implementation
Fix a typo
No, there is no implied or explicit change required

Fix typo in VariantEncoding

---

VariantEncoding.md

"to find a field with a given field" did not make sense in the context.
From what I understand, since the fields are listed in lexicographic order of the names, we are able to do a binary search using a given *name*, not a field ID.
Just a typo fix for the variant spec. No code changes.
No

MINOR: fix a typo in Variant Binary Encoding

---

VariantEncoding.md

When first reading the Variant encoding spec, it can be unclear that each Variant value begins with a single `value_metadata` byte composed of `value_header` and `basic_type`. This can be confusing, especially since “metadata” is also used to refer to the dictionary metadata structure.
The spec already uses the term `value_metadata` in prose, so labeling it clearly in the layout diagram helps reinforce understanding and reduce ambiguity.
- Added a clarifying comment (`<-- value_metadata`) to the value layout diagram to explicitly indicate that the first byte is `value_metadata`.
N/A — documentation-only change, no impact on implementations.

Minor: Clarify value_metadata in Variant value layout diagram

---

VariantShredding.md

From the test in https://github.com/apache/arrow-go/pull/455 which validates the cross-language variant implementation, we may need to update a few wording in the spec to make it clear 
- In variant array, either `value` and `typed_value` fields can be omitted but not both in array elements.

Spec: Clarify variant shredding spec

---

README.md

- Fixed grammatical error: changed "effect on" to "affect" (using the correct verb form with direct object)
Documentation change only - no functional changes requiring testing.

MINOR: Fix typo in README.md

---

src/main/thrift/parquet.thrift

- As can be seen on https://github.com/apache/parquet-format/issues/502 and the linked issues, the current state of Int96 is confusing. 
- Given there are proposed changes to various open source parquet writers to make them work better with Int96 despite it being deprecated, we should clarify the spec with respect to Int96 and statistics
- Closes https://github.com/apache/parquet-format/issues/502
1. Add comments clarifying that Int96 should not be written by new parquet writers (@rdblue's suggestion of what deprecated means in practice)
2. Add a recommendation on ordering of Int96 statistics to match what @rahulketch and @alkis are suggesting on https://github.com/apache/parquet-java/issues/3242 and https://github.com/apache/arrow-rs/issues/7686)
No -- in my mind this does not change the …

GH-502: Clarify Int96 status and add recommended ordering
